[project]
name = "agent-smith-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "groq>=1.7.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
sandbox = "sandbox_cli:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
